"""added venue table

Revision ID: 04c2211fa570
Revises: e3149f7c347b
Create Date: 2024-03-05 10:52:58.019087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04c2211fa570'
down_revision = 'e3149f7c347b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('venues',
    sa.Column('ven_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('location', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('ven_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('venues')
    # ### end Alembic commands ###
