"""added new table

Revision ID: 55859377d329
Revises: 3f325a0b2182
Create Date: 2024-03-07 12:57:32.482015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55859377d329'
down_revision = '3f325a0b2182'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('male', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('female', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('other', sa.Integer(), nullable=True))
        batch_op.drop_column('demographics')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('demographics', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.drop_column('other')
        batch_op.drop_column('female')
        batch_op.drop_column('male')

    # ### end Alembic commands ###
